"""Add estimated_fare

Revision ID: 530996b84a6f
Revises: 5e55c21a98f2
Create Date: 2026-02-15 12:00:11.466639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '530996b84a6f'
down_revision: Union[str, None] = '5e55c21a98f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ride_requests', sa.Column('estimated_fare', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ride_requests', 'estimated_fare')
    # ### end Alembic commands ###
